length = 0
width = 0
obstacle_number = 0
obstacle_safedist_occup = 0
obstacle_safedist_astar = 0
obstacle_radius = 0
length_start = 0
smooth_poly_n = 5
tubegen_poly_n = 5
lambda_max = 0
sim_step_length = 0.1
tube_r_max = 100
astarmap_scale = 100 # 100cm 为一个astar的采样点